class ErrorCode:
    # AUTHENTICATION_REQUIRED = "Authentication required."
    # AUTHORIZATION_FAILED = "Authorization failed. User has no access."
    # INVALID_TOKEN = "Invalid token."
    # INVALID_CREDENTIALS = "Invalid credentials."
    # EMAIL_TAKEN = "Email is already taken."
    # USERNAME_TAKEN = "Username is already taken."
    # REFRESH_TOKEN_NOT_VALID = "Refresh token is not valid."
    # REFRESH_TOKEN_REQUIRED = "Refresh token is required either in the body or cookie."
    # REFRESH_TOKEN_USER_NOT_EXISTS = "User with this refresh token not exists."
    # PASSWORD_NOT_MATCH="Passwords do not match"
    CHAT_PERMISSION_REQUIRED="User do not have permission to access this resource."
    CHAT_NOT_FOUND="Chat not found."
    ChatAlreadyExists="This direct chat already exists"
    ListOfTwoObjs="Must be a list of 2 objects"
    ChatUserNotExists="User not exists"
