version: '3.8'

services:

  # nginx:
  #   image: nginx:latest
  #   container_name: nginx
  #   ports:
  #     - "5002:5002"  # Expose Nginx on port 5002
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf  # Map the custom Nginx config
  #   depends_on:
  #     - backend
  #   networks:
  #     - fastapinetwork

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.prod
    ports:
      - 5001:5000
    volumes:
      - ./backend:/app
    command: uvicorn src.main:app --reload --host 0.0.0.0 --port 5000
    env_file:
      - ./.env.prod.db
    depends_on:
      - mysql
    networks:
      - fastapinetwork
      
  mysql:
    image: mysql:latest
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    container_name: mysql
    ports:
      - "3307:3306"
    env_file:
      - ./.env.prod.db
    volumes:
      - ./entrypoints/mysql:/docker-entrypoint-initdb.d
    networks:
      - fastapinetwork

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - './:/app'
      - '/app/node_modules'
    ports:
      - '82:80'
    depends_on:
      - backend
    networks:
      - fastapinetwork

  
networks:
    fastapinetwork:
        driver: bridge
