services:

  backend:
    build: ./backend
    dockerfile: ./backend/Dockerfile.prod
    ports:
      - 5000:5000
    volumes:
      - ./backend:/app
    # command: uvicorn src.main:app --reload --host 0.0.0.0 --port 5000
    environment:
      - APP_SECRET_STRING=admin
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=admin
      - DATABASE=db
      - DATABASE_TEST=test
      - DATABASE_HOST=mysql
      - DATABASE_SOCKET=3306
    depends_on:
      - mysql
      - frontend

  mysql:
    image: mysql:latest
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      # - MYSQL_DATABASE=db
    volumes:
      - ./entrypoints/mysql:/docker-entrypoint-initdb.d

  frontend:
    build: ./frontend
    dockerfile: ./frontend/Dockerfile
    volumes:
      - './:/app'
      - '/app/node_modules'
    ports:
      - '80:80'
    depends_on:
      - backend
