apiVersion: batch/v1
kind: Job
metadata:
  name: alembic-migrate
spec:
  template:
    spec:
      containers:
        - name: webregi-v2-app
          image: banderosik/banderachat-backend:latest
          command: ["/bin/sh","-c"]
          args: ["alembic upgrade head"]
          env:
          - name: DATABASE_HOST
            valueFrom:
              secretKeyRef:
                name: banderachat-secrets
                key: DATABASE_HOST
          - name: DATABASE_USERNAME
            valueFrom:
              secretKeyRef:
                name: banderachat-secrets
                key: DATABASE_USERNAME
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: banderachat-secrets
                key: DATABASE_PASSWORD
          - name: DATABASE
            valueFrom:
              secretKeyRef:
                name: banderachat-secrets
                key: DATABASE
          - name: DATABASE_SOCKET
            valueFrom:
              secretKeyRef:
                name: banderachat-secrets
                key: DATABASE_SOCKET
      restartPolicy: Never
  backoffLimit: 5
  ttlSecondsAfterFinished: 100
