---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: images-volume
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      volumes:
        - name: images-volume
          persistentVolumeClaim:
            claimName: images-volume
      containers:
      - name: backend
        image: banderosik/banderachat-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_HOST
          valueFrom:
            secretKeyRef:
              name: banderachat-secrets
              key: DATABASE_HOST
        - name: DATABASE_USERNAME
          valueFrom:
            secretKeyRef:
              name: banderachat-secrets
              key: DATABASE_USERNAME
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: banderachat-secrets
              key: DATABASE_PASSWORD
        - name: DATABASE
          valueFrom:
            secretKeyRef:
              name: banderachat-secrets
              key: DATABASE
        - name: DATABASE_SOCKET
          valueFrom:
            secretKeyRef:
              name: banderachat-secrets
              key: DATABASE_SOCKET
        volumeMounts:
          - name: images-volume
            mountPath: /app/media
---

apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: ClusterIP
  ports:
    - name: "backend"
      port: 8000
  selector:
    app: backend

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend
  annotations:
    dev.okteto.com/generate-host: backend
spec:
  rules:
    - http:
        paths:
          - backend:
              service:
                name: backend
                port:
                  number: 8000
            path: /
            pathType: ImplementationSpecific
