apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-set
spec:
  selector:
    matchLabels:
      app: mysql
  serviceName: "mysql"
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mysql
        image: mysql
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-store
          mountPath: /var/lib/mysql
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: banderachat-secrets
                key: DATABASE_PASSWORD
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: banderachat-secrets
                key: DATABASE
        resources:
          limits:
            cpu: 512m
            memory: 1028Mi
          requests:
            cpu: 256m
            memory: 512Mi
---
  # updateStrategy:
  #   rollingUpdate:
  #     partition: 0
  #   type: RollingUpdate
  volumeClaimTemplates:
  - metadata:
      name: mysql-store
    spec:
      storageClassName: fast-storageclass
      volumeMode: Filesystem
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 5Gi


---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service 
  labels:
    app: mysql
spec:
  ports:
  - port: 3306
    name: mysql
  type: NodePort
  selector:
    app: mysql
